Create database August_Major_project
use August_Major_project

Select * from dbo.factTable

Select * from dbo.LocationTable

Select * from dbo.ProductTable

-- 1. Display the number of states present in the LocationTable
Select  State,  count(State) as numberOfState
from LocationTable
Group By state

--2. How many products are of regular type
Select count(Type) As RegularTypeProduct
from ProductTable
Where Type='regular'

-- 3. How much spending has been done on marketing of product ID 1
SELECT SUM(Marketing) AS TotalMarketingSpend
FROM FactTable
WHERE ProductID = 1

--4. what is Minimum sales of a product
Select min(Sales) As MinimumSales
from factTable

-- 5. Display the maximum Cost of Goods Sold (COGS)
Select max(COGS) As MaximumCOGS
from factTable

-- 6. Display the details of products where Product Type = 'Coffee'
Select * from ProductTable
where Product_Type='Coffee'

--7.Display the deatils where Total Expenses > 40
Select * 
from factTable
where Total_Expenses>40


--8. What is average sales in area code 719
Select avg(Sales) As AverageSales
from factTable
where Area_Code=719

--9.Find out the total profit generated by Colorado state
Select sum(Profit) As TotalProfit
from factTable As fact
Inner Join LocationTable as loc
on fact.Area_Code=loc.Area_Code
where State ='Colorado'

--10. Display the average inventory for each product ID
Select ProductId, avg(Inventory) As AverageInventory
from factTable
Group By ProductId

--11. Dispaly state in a sequential order in a Location Table
Select Distinct State 
from LocationTable
Order By State Asc

--12. Display the average budget of products where average budget margin > 100
Select  ProductId, avg(Budget_Sales) As AverageBudgetSales
from factTable
Group By  ProductId
Having Avg(Budget_Margin) >100

--13. What is the total sales done on date 2010-01-01
Select sum(Sales) As TotalSales
from factTable
where Date ='2010-01-01'

--14. Display the average total expense of each product on individual date
Select Date, ProductId, Avg(Total_Expenses) As AverageTotalExpenses
from factTable
Group by  Date, ProductId

--15. Display table with the following attributes  such as date, productId,
--product_type, Product, sales, profit, state, area_code 
Select Date, fact.ProductId, pro.Product_Type, pro.Product, fact.Sales, fact.Profit, loc.State, fact.Area_Code
from factTable As fact
Inner Join ProductTable As pro
ON fact.ProductId=pro.ProductId
Inner Join  LocationTable As loc
ON fact.Area_Code=loc.Area_Code

--16. Display the rank without any gap to show the sales wise rank
Select ProductId, Date, Sales,
	DENSE_RANK() Over (Partition By ProductId Order by Sales desc) as RankSales
	from factTable

--17.Find the state wise profit and sales
Select  loc.State, sum(fact.Profit) As TotalProfit, sum(fact.Sales) As TotalSales
from factTable As fact
Inner Join LocationTable As loc
ON fact.Area_Code=loc.Area_Code
Group By loc.State

-- 18. Find the state wise profit and sales along with the product name
Select pro.Product, loc.State, sum(fact.Profit) As TotalProfit, sum(fact.Sales) As TotalSales
from factTable As fact
Inner Join LocationTable As loc
ON fact.Area_Code=loc.Area_Code
Inner Join ProductTable as pro
ON fact.ProductId=pro.ProductId
Group By loc.State, pro.Product

--19. If there is increase in sales of 5%, calculate the increasedSales
Select Sales, Sales*1.05 As IncreasedSales
from factTable

--20. Find the maximum profit along with the product Id and product type
Select fact.ProductId, pro.Product_Type, max(Profit) As MaximumProfit
from factTable as fact
Inner Join ProductTable as pro
ON fact.ProductId=pro.ProductId
Group By fact.ProductId, pro.Product_Type

-- 21. Create a Stored procedure to fetch the result according to the product type from 
--product table

Create or alter Procedure csp_GetProductType
@ProductType varchar(20)
AS
Begin
	Select * from ProductTable
	Where Product_Type=@ProductType
End

Exec dbo.csp_GetProductType  @ProductType= 'coffee'

--22. Write a query by creating a condition in which if the total expenses is less than 60 then it is 
-- a profit or else loss

Select *, 
	Case When Total_Expenses < 60 Then 'Profit'
	Else 'Loss'
	End  As Status
From factTable

-- 23. Give the total weekly sales value with the date and product id details. Use roll-up to pull the 
--data in hierarchial order

Select Datepart(Week, Date) As WeekNumber, ProductId, sum(Sales) As WeeklySales
from factTable
Group by RollUp(DATEPART(Week,Date), ProductId)

-- 24. Apply union and intersection operator on the tables which  consist of attribute area code
Select  Area_Code
from factTable
Union
Select Area_Code 
from LocationTable

Select  Area_Code
from factTable
Intersect
Select Area_Code 
from LocationTable

--25.Create a User-defined function for the product table to fetch a particular product type based 
--upon the user's preference.

Create or alter Function fn_GetProductType(
@ProductType varchar(20)
)
Returns table
AS
Return(
	Select * from ProductTable 
	where Product_Type=@ProductType
)

Select * from dbo.fn_GetProductType('Tea') as ProcuctType

--26. change the product type from coffee to tea where product id is 1 and undo it.
Select * 
into ProductTable_Backup
from ProductTable

Select * from ProductTable_Backup

--Coffee to tea
Update ProductTable 
Set Product_type='Tea'
Where ProductId=1

Select * from ProductTable

--undo
Update ProductTable 
Set Product_type='Coffee'
Where ProductId=1

Select * from ProductTable

-- 27. Display the date, product id and sales where total expenses are between 100 to 200
Select Date, ProductID, Sales
From factTable
Where Total_Expenses BETWEEN 100 AND 200

--28. Delete the records in the product table for regular type

Delete from ProductTable
where Type='Regular'

Select * from ProductTable

-- 29.Display the Ascii value of the fifth character from the columnproduct
Select Product,
       ASCII(SUBSTRING(Product, 5, 1)) AS FifthCharASCII
FROM ProductTable